Add Stakdeks free QR code generator.
n0shake/Public-APIs pull request #399
Opened 2020-11-30 12:07 UTC by Stakdek

This PR adds the Free QR-Code generator API

2020-11-30 12:25 UTC, Stakdek commented
Feel free to review!

2020-11-30 14:32 UTC, n0shake approved these changes

2020-11-30 14:33 UTC, n0shake requested changes
Can you arrange this alphabetically?

2020-12-01 08:04 UTC, Stakdek commented
I have arranged this alphabetically :)

2020-12-01 13:55 UTC, n0shake approved these changes

2020-12-01 13:55 UTC, merged